# Generated by Django 4.1.3 on 2022-11-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_Finance',
        ),
        migrations.AddField(
            model_name='user',
            name='is_HR',
            field=models.BooleanField(default=False),
        ),
    ]
